#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config normal_border_color "#1F1F1F"
bspc config focused_border_color "#1976D2"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#1976D2"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


#      Autostart 
/home/sidharth/.config/polybar/launch.sh --shapes
feh --bg-fill /home/sidharth/Downloads/tavr2cfgft291.jpg
/usr/bin/gnome-keyring-daemon --start --components=secrets 
/usr/libexec/gsd-xsettings